sudo: required
services:
  - docker

before_install:
  - docker build -t ghoshsaurabh/react-docker-with-ci -f Dockerfile.dev .

script:
  - docker run ghoshsaurabh/react-docker-with-ci npm run test -- --coverage
